springfox:
  documentation:
    swagger:
      v2:
        path: api-docs

server:
  port: 8080

spring:
  jackson:
    date-format: ch.uzh.ifi.hase.soprafs21.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  # Enabling the H2-Console (local and remote)
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
#    removing the MODE=Postgres since it's not compatible with the GeoDBDialect and the DB initialization fails
#    unfortunately, the PostgisDialect doesn't work since there's a Geometry conversion that fails during DB insert.
    url: jdbc:h2:mem:soprafsdb;IGNORECASE=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS soprafs21
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
    initialization-mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      default_schema: soprafs21
      hbm2ddl:
        auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
      javax:
        persistence:
          create-database-schemas: true
