springfox:
  documentation:
    swagger:
      v2:
        path: api-docs

server:
  port: 8080

spring:
  jackson:
    date-format: ch.uzh.ifi.hase.soprafs21.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  # Enabling the H2-Console (local and remote)
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:soprafsdb;MODE=PostgreSQL;IGNORECASE=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS soprafs21
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    platform: h2
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true

hibernate:
  default_schema: soprafs21
  hbm2ddl: 
    auto: update
