# Heroku Postgres DB Settings
spring:
  profiles: prod
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

# Hibernate ddl auto (create, create-drop, update): with "update" the database
# schema will be automatically updated accordingly to java entities found in project
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

hibernate:
  default_schema: soprafs21
  hbm2ddl:
    auto: update

javax:
  persistence:
    create-database-schemas: true