# Heroku Postgres DB Settings
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

# Hibernate ddl auto (create, create-drop, update): with "update" the database
# schema will be automatically updated accordingly to java entities found in project
  jpa:
    hibernate:
      default_schema: soprafs21
      hbm2ddl:
        auto: update
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1057742566572-4ufig26uc1s8tiggp6ja3tf13s4iuo87.apps.googleusercontent.com
            clientSecret: tm10uDPQnBy0HHYv4xS5xmtR

javax:
  persistence:
    create-database-schemas: true