
--
-- Create test users
INSERT INTO SOPRAFS21.USERS(ID, EMAIL, NAME, PROFILE_PICTUREURL, PROVIDER, PROVIDER_UID, STATUS, TOKEN)
VALUES (1, 'mark@twen.de', 'Mark', 'SomeURL', 'GoogleProvider', 'SOME_GOOGLE_ID', 'ONLINE', 'DUMMYTOKEN');
INSERT INTO SOPRAFS21.USERS(ID, EMAIL, NAME, PROFILE_PICTUREURL, PROVIDER, PROVIDER_UID, STATUS, TOKEN)
VALUES (2, 'mark2@twen.de', 'Mark2', 'SomeURL', 'GoogleProvider', 'SOME_GOOGLE_IDj', 'ONLINE', 'DUMMYTOKENj');
INSERT INTO SOPRAFS21.USERS(ID, EMAIL, NAME, PROFILE_PICTUREURL, PROVIDER, PROVIDER_UID, STATUS, TOKEN)
VALUES (3, 'mark3@twen.de', 'Mark3', 'SomeURL', 'GoogleProvider', 'SOME_GOOGLE_IDl', 'ONLINE', 'DUMMYTOKENh');
-- Create conversation
INSERT INTO SOPRAFS21.CONVERSATIONS(ID, participant1_id, PARTICIPANT2_ID)
VALUES (1, 1, 2);
INSERT INTO SOPRAFS21.CONVERSATIONS(ID, participant1_id, PARTICIPANT2_ID)
VALUES (2, 1, 3);
-- Create test messages
INSERT INTO SOPRAFS21.MESSAGES(ID, MESSAGE, TIME_STAMP, UNREAD, RECEIVER_ID, SENDER_ID, CONVERSATION_ID)
VALUES (1, 'privet', TO_TIMESTAMP( '2013-03-05', 'yyyy-mm-dd' ), true, 1, 2, 1);
INSERT INTO SOPRAFS21.MESSAGES(ID, MESSAGE, TIME_STAMP, UNREAD, RECEIVER_ID, SENDER_ID, CONVERSATION_ID)
VALUES (2, 'poka', TO_TIMESTAMP( '2013-03-06', 'yyyy-mm-dd' ), true, 1, 2, 1);
INSERT INTO SOPRAFS21.MESSAGES(ID, MESSAGE, TIME_STAMP, UNREAD, RECEIVER_ID, SENDER_ID, CONVERSATION_ID)
VALUES (3, 'privet kak dela', TO_TIMESTAMP( '2013-03-04', 'yyyy-mm-dd' ), true, 2, 1, 1);
INSERT INTO SOPRAFS21.MESSAGES(ID, MESSAGE, TIME_STAMP, UNREAD, RECEIVER_ID, SENDER_ID, CONVERSATION_ID)
VALUES (4, 'dosvidania', TO_TIMESTAMP( '2013-03-11', 'yyyy-mm-dd' ), true, 2, 1, 1);
INSERT INTO SOPRAFS21.MESSAGES(ID, MESSAGE, TIME_STAMP, UNREAD, RECEIVER_ID, SENDER_ID, CONVERSATION_ID)
VALUES (5, 'dosvidaniaagain', TO_TIMESTAMP( '2013-03-03', 'yyyy-mm-dd' ), true, 2, 1, 1);