PUT http://localhost:8080/v1/users/1/location
Authorization: Bearer {{email}}
Content-Type: application/json

{
    "longitude": 47.35997146785179,
    "latitude": 8.461859195948641
}

###

GET {{backend-url}}/v1/users/1
Authorization: Bearer {{email}}
Content-Type: application/json

###
PUT https://sopra-fs21-test.herokuapp.com/v1/users/2/location
Content-Type: application/json

{
    "longitude": 47.35997146785179,
    "latitude": 8.461859195948641
}

###

GET http://localhost:8080/v1/users/area?visibleArea%5B0%5D.longitude=8.4401162&visibleArea%5B0%5D.latitude=47.3784542&visibleArea%5B1%5D.longitude=8.4649656&visibleArea%5B1%5D.latitude=47.3760936&visibleArea%5B2%5D.longitude=8.4779352&visibleArea%5B2%5D.latitude=47.3588282&visibleArea%5B3%5D.longitude=8.4563555&visibleArea%5B3%5D.latitude=47.3451373&visibleArea%5B4%5D.longitude=8.4277460&visibleArea%5B4%5D.latitude=47.3481267&visibleArea%5B5%5D.longitude=8.4258387&visibleArea%5B5%5D.latitude=47.3660966&visibleArea%5B6%5D.longitude=8.4398437&visibleArea%5B6%5D.latitude=47.3785280&visibleArea%5B7%5D.longitude=8.4401162&visibleArea%5B7%5D.latitude=47.3784542
Content-Type: application/json

###

GET http://localhost:8080/v1/users/
Content-Type: application/json

###

POST {{backend-url}}/v1/users/1/dogs/
Authorization: Bearer {{email}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="dogDto"; filename="data.json"
Content-Type: application/json

< ./request-form-data.json

--WebAppBoundary
Content-Disposition: form-data; name="profilePicture"; filename="test.png"
Content-Type: image/png

< ./test_img.png

--WebAppBoundary--

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("Response content-type is json", function() {
  var type = response.contentType.mimeType;
  client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
});
%}

###

GET {{backend-url}}/v1/users/1/conversations
Content-Type: application/json
Authorization: Bearer mark@twen.de

###
POST {{backend-url}}/v1/message
Content-Type: application/json
Authorization: Bearer mark@twen.de

{
    "senderId": 1,
    "receiverId": 3,
    "message": "bangbang"
}
###
DELETE {{backend-url}}/v1/users/1
Authorization: Bearer {{email}}
Content-Type: application/json

###
POST {{backend-url}}/v1/parks
Authorization: Bearer {{email}}
Content-Type: application/json

{
    "creatorId": 1,
    "coordinate": {"longitude": 8.461859195948641, "latitude": 47.35997146785179}
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

###
GET http://localhost:8080/v1/parks?visibleArea%5B0%5D.longitude=21.250008151313587&visibleArea%5B0%5D.latitude=44.454432889526544&visibleArea%5B1%5D.longitude=19.878364541371496&visibleArea%5B1%5D.latitude=50.821909691742334&visibleArea%5B2%5D.longitude=6.817267806429448&visibleArea%5B2%5D.latitude=52.54943251691744&visibleArea%5B3%5D.longitude=2.234321572621498&visibleArea%5B3%5D.latitude=44.420452461356874
Authorization: Bearer {{email}}
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Check if the new park is included", function (){
    client.assert(response.body.length === 1 );
});
%}
###

DELETE {{backend-url}}/v1/parks/1
Authorization: Bearer {{email}}
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}
###
POST {{backend-url}}/v1/users/1/tags
Authorization: Bearer {{email}}
Content-Type: application/json

{
    "name": "somethingee6",
    "tagType": "OFFERING"
}

###