###
# Checks the current dogs list size
GET {{backend-url}}/v1/users/1
Authorization: Bearer {{email}}

> {%
    client.log("Current list of dogs: " + response.body.dogs);
    client.global.set("dogsListSize", response.body.dogs.length );
 %}

###
# Creates a dog
POST {{backend-url}}/v1/users/1/dogs/
Authorization: Bearer {{email}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="dogDto"; filename="data.json"
Content-Type: application/json

< ./request-form-data.json

--WebAppBoundary
Content-Disposition: form-data; name="profilePicture"; filename="test.png"
Content-Type: image/png

< ./test_img.png

--WebAppBoundary--

> {%
    client.test("Request executed successfully", function() {
    client.assert(response.status === 201, "Response status is not 201");
});
%}

###
# Checks the current dogs list size
GET {{backend-url}}/v1/users/1
Authorization: Bearer {{email}}

> {%
     client.test("Check if the new dog is included", function (){
     client.assert(response.body.dogs.length === parseInt(client.global.get("dogsListSize")) + 1 );
 });
 %}
